server:
  port: 8810

debug: true

spring:
  application:
    name: grib-json
  data:
    mongodb:
      host: 192.168.201.57
      port: 27017
      database: zgssWeather
      username: zgss
      password: zgss

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.201.57:8761/eureka/

dataRoot: /data51/pub/data/gfs1p00

activemq:
  url: failover://tcp://192.168.201.57:61616
  user: admin
  password: admin
  queueName: grib_data
  contourQueueName: grib_contour

cron:
  toJson: 0 0 0 * * ?

