server:
  port: 8810

debug: true

spring:
  application:
    name: grib-json
  data:
    mongodb:
      host: localhost
      port: 27017
      database: zgssWeather
      username: zgss
      password: zgss

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/

dataRoot: E:\资料\紫光陕数\气象项目\通用项目\数据库

activemq:
  url: failover://tcp://localhost:61616
  user: admin
  password: admin
  queueName: grib_data
  contourQueueName: grib_contour

cron:
  toJson: 0 25 9 * * ?

