package com.zgss.grib.gribdata.base;

import com.zgss.grib.gribdata.entity.Component_of_wind;

import java.util.List;

public interface IBaseService<T,PK> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Component_of_wind
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(PK key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Component_of_wind
     *
     * @mbggenerated
     */
    int insert(T record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Component_of_wind
     *
     * @mbggenerated
     */
    int insertSelective(T record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Component_of_wind
     *
     * @mbggenerated
     */
    T selectByPrimaryKey(PK key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Component_of_wind
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(T record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Component_of_wind
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(T record);

    PK getKey(T record);
    boolean exists(PK key);
    void upSert(T record);
    void upSert(List<T> records);
    int insertBatch(List<T> records);
}
