package com.zgss.grib.gribdata.entity;

import java.util.Date;

public class Component_of_windKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Component_of_wind.refTime
     *
     * @mbggenerated
     */
    private Date reftime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Component_of_wind.surfaceValue
     *
     * @mbggenerated
     */
    private Integer surfacevalue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Component_of_wind.refTime
     *
     * @return the value of Component_of_wind.refTime
     *
     * @mbggenerated
     */
    public Date getReftime() {
        return reftime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Component_of_wind.refTime
     *
     * @param reftime the value for Component_of_wind.refTime
     *
     * @mbggenerated
     */
    public void setReftime(Date reftime) {
        this.reftime = reftime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Component_of_wind.surfaceValue
     *
     * @return the value of Component_of_wind.surfaceValue
     *
     * @mbggenerated
     */
    public Integer getSurfacevalue() {
        return surfacevalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Component_of_wind.surfaceValue
     *
     * @param surfacevalue the value for Component_of_wind.surfaceValue
     *
     * @mbggenerated
     */
    public void setSurfacevalue(Integer surfacevalue) {
        this.surfacevalue = surfacevalue;
    }
}