package com.zgss.grib.gribdata.entity;

public class Component_of_wind extends Component_of_windKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Component_of_wind.lon
     *
     * @mbggenerated
     */
    private Double lon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Component_of_wind.lat
     *
     * @mbggenerated
     */
    private Double lat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Component_of_wind.value
     *
     * @mbggenerated
     */
    private Double value;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Component_of_wind.lon
     *
     * @return the value of Component_of_wind.lon
     *
     * @mbggenerated
     */
    public Double getLon() {
        return lon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Component_of_wind.lon
     *
     * @param lon the value for Component_of_wind.lon
     *
     * @mbggenerated
     */
    public void setLon(Double lon) {
        this.lon = lon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Component_of_wind.lat
     *
     * @return the value of Component_of_wind.lat
     *
     * @mbggenerated
     */
    public Double getLat() {
        return lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Component_of_wind.lat
     *
     * @param lat the value for Component_of_wind.lat
     *
     * @mbggenerated
     */
    public void setLat(Double lat) {
        this.lat = lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Component_of_wind.value
     *
     * @return the value of Component_of_wind.value
     *
     * @mbggenerated
     */
    public Double getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Component_of_wind.value
     *
     * @param value the value for Component_of_wind.value
     *
     * @mbggenerated
     */
    public void setValue(Double value) {
        this.value = value;
    }
}