package com.zgss.grib.gribdata.entity;

public class Geopotential_height extends Geopotential_heightKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Geopotential_height.lon
     *
     * @mbggenerated
     */
    private Double lon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Geopotential_height.lat
     *
     * @mbggenerated
     */
    private Double lat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Geopotential_height.value
     *
     * @mbggenerated
     */
    private Double value;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Geopotential_height.lon
     *
     * @return the value of Geopotential_height.lon
     *
     * @mbggenerated
     */
    public Double getLon() {
        return lon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Geopotential_height.lon
     *
     * @param lon the value for Geopotential_height.lon
     *
     * @mbggenerated
     */
    public void setLon(Double lon) {
        this.lon = lon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Geopotential_height.lat
     *
     * @return the value of Geopotential_height.lat
     *
     * @mbggenerated
     */
    public Double getLat() {
        return lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Geopotential_height.lat
     *
     * @param lat the value for Geopotential_height.lat
     *
     * @mbggenerated
     */
    public void setLat(Double lat) {
        this.lat = lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Geopotential_height.value
     *
     * @return the value of Geopotential_height.value
     *
     * @mbggenerated
     */
    public Double getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Geopotential_height.value
     *
     * @param value the value for Geopotential_height.value
     *
     * @mbggenerated
     */
    public void setValue(Double value) {
        this.value = value;
    }
}