package com.zgss.grib.gribdata.entity;

import com.fasterxml.jackson.annotation.JsonIgnore;
import org.springframework.data.mongodb.core.geo.GeoJsonPoint;
import org.springframework.data.mongodb.core.index.CompoundIndex;
import org.springframework.data.mongodb.core.index.CompoundIndexes;
import org.springframework.data.mongodb.core.index.GeoSpatialIndexType;
import org.springframework.data.mongodb.core.index.GeoSpatialIndexed;
import org.springframework.data.mongodb.core.mapping.Document;

@Document
@CompoundIndexes({@CompoundIndex(name = "reftime_surfacevalue",def = "{'reftime':1,'surfacevalue':1}")})
public class Weather extends WeatherKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Component_of_wind.lon
     *
     * @mbggenerated
     */
    private Double lon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Component_of_wind.lat
     *
     * @mbggenerated
     */
    private Double lat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Component_of_wind.value
     *
     * @mbggenerated
     */
    private Double value;

    public GeoJsonPoint getLocation() {
        return location;
    }

    public void setLocation(GeoJsonPoint location) {
        this.location = location;
    }

    @JsonIgnore
    @GeoSpatialIndexed(type= GeoSpatialIndexType.GEO_2DSPHERE)
    private GeoJsonPoint location;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Component_of_wind.lon
     *
     * @return the value of Component_of_wind.lon
     *
     * @mbggenerated
     */
    public Double getLon() {
        return lon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Component_of_wind.lon
     *
     * @param lon the value for Component_of_wind.lon
     *
     * @mbggenerated
     */
    public void setLon(Double lon) {
        this.lon = lon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Component_of_wind.lat
     *
     * @return the value of Component_of_wind.lat
     *
     * @mbggenerated
     */
    public Double getLat() {
        return lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Component_of_wind.lat
     *
     * @param lat the value for Component_of_wind.lat
     *
     * @mbggenerated
     */
    public void setLat(Double lat) {
        this.lat = lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Component_of_wind.value
     *
     * @return the value of Component_of_wind.value
     *
     * @mbggenerated
     */
    public Double getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Component_of_wind.value
     *
     * @param value the value for Component_of_wind.value
     *
     * @mbggenerated
     */
    public void setValue(Double value) {
        this.value = value;
    }
}