package com.zgss.grib.gribservice.mapper;
import com.zgss.grib.gribservice.entity.Legend;
import com.zgss.grib.gribservice.entity.LegendKey;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

@Mapper
public interface LegendMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Legend
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(LegendKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Legend
     *
     * @mbggenerated
     */
    int insert(Legend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Legend
     *
     * @mbggenerated
     */
    int insertSelective(Legend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Legend
     *
     * @mbggenerated
     */
    Legend selectByPrimaryKey(LegendKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Legend
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Legend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Legend
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Legend record);

    /**
     *  获取指定参数的图例列表
     * @param param
     * @return
     */
    List<Legend> selectAll(Map<String, Object> param);

    Double[] selectBreaks(@Param("parameterNumberName") String parameterNumberName);
}