package com.zgss.grib.contour.entity;

public class Legend extends LegendKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Legend.max
     *
     * @mbggenerated
     */
    private Double max;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Legend.min
     *
     * @mbggenerated
     */
    private Double min;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Legend.caption
     *
     * @mbggenerated
     */
    private String caption;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Legend.colorHex
     *
     * @mbggenerated
     */
    private String colorhex;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Legend.max
     *
     * @return the value of Legend.max
     *
     * @mbggenerated
     */
    public Double getMax() {
        return max;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Legend.max
     *
     * @param max the value for Legend.max
     *
     * @mbggenerated
     */
    public void setMax(Double max) {
        this.max = max;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Legend.min
     *
     * @return the value of Legend.min
     *
     * @mbggenerated
     */
    public Double getMin() {
        return min;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Legend.min
     *
     * @param min the value for Legend.min
     *
     * @mbggenerated
     */
    public void setMin(Double min) {
        this.min = min;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Legend.caption
     *
     * @return the value of Legend.caption
     *
     * @mbggenerated
     */
    public String getCaption() {
        return caption;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Legend.caption
     *
     * @param caption the value for Legend.caption
     *
     * @mbggenerated
     */
    public void setCaption(String caption) {
        this.caption = caption == null ? null : caption.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Legend.colorHex
     *
     * @return the value of Legend.colorHex
     *
     * @mbggenerated
     */
    public String getColorhex() {
        return colorhex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Legend.colorHex
     *
     * @param colorhex the value for Legend.colorHex
     *
     * @mbggenerated
     */
    public void setColorhex(String colorhex) {
        this.colorhex = colorhex == null ? null : colorhex.trim();
    }

    @Override
    public String toString() {
        return "Legend{" +
                "max=" + max +
                ", min=" + min +
                ", caption='" + caption + '\'' +
                ", colorhex='" + colorhex + '\'' +
                '}';
    }
}