package com.zgss.grib.contour.entity;

public class Relative_humidity extends Relative_humidityKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Relative_humidity.lon
     *
     * @mbggenerated
     */
    private Double lon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Relative_humidity.lat
     *
     * @mbggenerated
     */
    private Double lat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Relative_humidity.value
     *
     * @mbggenerated
     */
    private Double value;

    public String getGeojson() {
        return geojson;
    }

    public void setGeojson(String geojson) {
        this.geojson = geojson;
    }

    private String geojson;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Relative_humidity.lon
     *
     * @return the value of Relative_humidity.lon
     *
     * @mbggenerated
     */
    public Double getLon() {
        return lon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Relative_humidity.lon
     *
     * @param lon the value for Relative_humidity.lon
     *
     * @mbggenerated
     */
    public void setLon(Double lon) {
        this.lon = lon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Relative_humidity.lat
     *
     * @return the value of Relative_humidity.lat
     *
     * @mbggenerated
     */
    public Double getLat() {
        return lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Relative_humidity.lat
     *
     * @param lat the value for Relative_humidity.lat
     *
     * @mbggenerated
     */
    public void setLat(Double lat) {
        this.lat = lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Relative_humidity.value
     *
     * @return the value of Relative_humidity.value
     *
     * @mbggenerated
     */
    public Double getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Relative_humidity.value
     *
     * @param value the value for Relative_humidity.value
     *
     * @mbggenerated
     */
    public void setValue(Double value) {
        this.value = value;
    }
}